export const CART_GIFTS_REQUEST_CONFIG = 'CART_GIFTS_REQUEST_CONFIG';
export const CART_GIFTS_RECEIVE_CONFIG = 'CART_GIFTS_RECEIVE_CONFIG';
export const CART_GIFTS_ERROR_CONFIG = 'CART_GIFTS_ERROR_CONFIG';
export const CART_GIFTS_FIZZLE_PRODUCTS = 'CART_GIFTS_FIZZLE_PRODUCTS';

export const DATA_LIFETIME = 36e5; // 1 hour in milliseconds
